/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssignedCandidate = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'assignDate' : IDL.Text,
  'assignedTo' : IDL.Text,
  'campaign' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Text,
  'batchId' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});
export const Client = IDL.Record({
  'id' : IDL.Text,
  'contactName' : IDL.Text,
  'activeRoles' : IDL.Text,
  'createdAt' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'contactName' : IDL.Text,
  'urgency' : IDL.Text,
  'role' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'emailAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'positions' : IDL.Text,
  'followUpDate' : IDL.Text,
});
export const SignupRequest = IDL.Record({
  'status' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'requestedAt' : Time,
});
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'salary' : IDL.Text,
  'createdAt' : IDL.Text,
  'role' : IDL.Text,
  'companyName' : IDL.Text,
  'campaignName' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAssignedCandidate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'approveSignupRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteCampaign' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteClient' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllAssignedCandidates' : IDL.Func(
      [],
      [IDL.Vec(AssignedCandidate)],
      ['query'],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getApprovedRecruiters' : IDL.Func([], [IDL.Vec(SignupRequest)], ['query']),
  'getAssignedCandidates' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AssignedCandidate)],
      ['query'],
    ),
  'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getSignupRequests' : IDL.Func([], [IDL.Vec(SignupRequest)], ['query']),
  'rejectSignupRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitSignupRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateCandidateStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssignedCandidate = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'assignDate' : IDL.Text,
    'assignedTo' : IDL.Text,
    'campaign' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Text,
    'batchId' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  const Client = IDL.Record({
    'id' : IDL.Text,
    'contactName' : IDL.Text,
    'activeRoles' : IDL.Text,
    'createdAt' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'contactName' : IDL.Text,
    'urgency' : IDL.Text,
    'role' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'emailAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'positions' : IDL.Text,
    'followUpDate' : IDL.Text,
  });
  const SignupRequest = IDL.Record({
    'status' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'requestedAt' : Time,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'salary' : IDL.Text,
    'createdAt' : IDL.Text,
    'role' : IDL.Text,
    'companyName' : IDL.Text,
    'campaignName' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addAssignedCandidate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'approveSignupRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteCampaign' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteClient' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllAssignedCandidates' : IDL.Func(
        [],
        [IDL.Vec(AssignedCandidate)],
        ['query'],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getApprovedRecruiters' : IDL.Func([], [IDL.Vec(SignupRequest)], ['query']),
    'getAssignedCandidates' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AssignedCandidate)],
        ['query'],
      ),
    'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getSignupRequests' : IDL.Func([], [IDL.Vec(SignupRequest)], ['query']),
    'rejectSignupRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitSignupRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateCandidateStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };