/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssignedCandidate {
  'id' : string,
  'status' : string,
  'assignDate' : string,
  'assignedTo' : string,
  'campaign' : string,
  'name' : string,
  'email' : string,
  'updatedAt' : string,
  'batchId' : string,
  'phone' : string,
  'skills' : string,
}
export interface Campaign {
  'id' : bigint,
  'salary' : string,
  'createdAt' : string,
  'role' : string,
  'companyName' : string,
  'campaignName' : string,
  'location' : string,
}
export interface Client {
  'id' : string,
  'contactName' : string,
  'activeRoles' : string,
  'createdAt' : string,
  'email' : string,
  'notes' : string,
  'companyName' : string,
  'phone' : string,
  'location' : string,
}
export interface SignupRequest {
  'status' : string,
  'password' : string,
  'name' : string,
  'email' : string,
  'requestedAt' : Time,
}
export interface Submission {
  'id' : bigint,
  'status' : string,
  'contactName' : string,
  'urgency' : string,
  'role' : string,
  'notes' : string,
  'timestamp' : Time,
  'companyName' : string,
  'emailAddress' : string,
  'phoneNumber' : string,
  'positions' : string,
  'followUpDate' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAssignedCandidate' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    boolean
  >,
  'approveSignupRequest' : ActorMethod<[string], boolean>,
  'createCampaign' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createClient' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    string
  >,
  'createSubmission' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'deleteCampaign' : ActorMethod<[bigint], boolean>,
  'deleteClient' : ActorMethod<[string], string>,
  'deleteSubmission' : ActorMethod<[bigint], boolean>,
  'getAllAssignedCandidates' : ActorMethod<[], Array<AssignedCandidate>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getApprovedRecruiters' : ActorMethod<[], Array<SignupRequest>>,
  'getAssignedCandidates' : ActorMethod<
    [string, string],
    Array<AssignedCandidate>
  >,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getSignupRequests' : ActorMethod<[], Array<SignupRequest>>,
  'rejectSignupRequest' : ActorMethod<[string], boolean>,
  'submitSignupRequest' : ActorMethod<[string, string, string], undefined>,
  'updateCandidateStatus' : ActorMethod<[string, string, string], boolean>,
  'updateClient' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'updateLead' : ActorMethod<[bigint, string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];