/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'contactName' : IDL.Text,
  'urgency' : IDL.Text,
  'role' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'emailAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'positions' : IDL.Text,
  'followUpDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'contactName' : IDL.Text,
    'urgency' : IDL.Text,
    'role' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'emailAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'positions' : IDL.Text,
    'followUpDate' : IDL.Text,
  });
  
  return IDL.Service({
    'createSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteSubmission' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };