/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AssignedCandidate {
    id: string;
    status: string;
    assignDate: string;
    assignedTo: string;
    campaign: string;
    name: string;
    email: string;
    updatedAt: string;
    batchId: string;
    phone: string;
    skills: string;
}
export type Time = bigint;
export interface Submission {
    id: bigint;
    status: string;
    contactName: string;
    urgency: string;
    role: string;
    notes: string;
    timestamp: Time;
    companyName: string;
    emailAddress: string;
    phoneNumber: string;
    positions: string;
    followUpDate: string;
}
export interface Client {
    id: string;
    contactName: string;
    activeRoles: string;
    createdAt: string;
    email: string;
    notes: string;
    companyName: string;
    phone: string;
    location: string;
}
export interface Campaign {
    id: bigint;
    salary: string;
    createdAt: string;
    role: string;
    companyName: string;
    campaignName: string;
    location: string;
}
export interface SignupRequest {
    status: string;
    password: string;
    name: string;
    email: string;
    requestedAt: Time;
}
export interface backendInterface {
    addAssignedCandidate(id: string, name: string, phone: string, email: string, skills: string, assignedTo: string, campaign: string, batchId: string, assignDate: string): Promise<boolean>;
    approveSignupRequest(email: string): Promise<boolean>;
    createCampaign(campaignName: string, companyName: string, role: string, location: string, salary: string): Promise<bigint>;
    createClient(id: string, companyName: string, contactName: string, phone: string, email: string, location: string, activeRoles: string, notes: string, createdAt: string): Promise<string>;
    createSubmission(companyName: string, contactName: string, phoneNumber: string, emailAddress: string, role: string, positions: string, urgency: string): Promise<void>;
    deleteCampaign(id: bigint): Promise<boolean>;
    deleteClient(id: string): Promise<string>;
    deleteSubmission(id: bigint): Promise<boolean>;
    getAllAssignedCandidates(): Promise<Array<AssignedCandidate>>;
    getAllClients(): Promise<Array<Client>>;
    getAllSubmissions(): Promise<Array<Submission>>;
    getApprovedRecruiters(): Promise<Array<SignupRequest>>;
    getAssignedCandidates(recruiterEmail: string, campaign: string): Promise<Array<AssignedCandidate>>;
    getCampaigns(): Promise<Array<Campaign>>;
    getSignupRequests(): Promise<Array<SignupRequest>>;
    rejectSignupRequest(email: string): Promise<boolean>;
    submitSignupRequest(name: string, email: string, password: string): Promise<void>;
    updateCandidateStatus(id: string, status: string, updatedAt: string): Promise<boolean>;
    updateClient(id: string, companyName: string, contactName: string, phone: string, email: string, location: string, activeRoles: string, notes: string): Promise<string>;
    updateLead(id: bigint, status: string, notes: string, followUpDate: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAssignedCandidate(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAssignedCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAssignedCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async approveSignupRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSignupRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSignupRequest(arg0);
            return result;
        }
    }
    async createCampaign(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createSubmission(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubmission(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubmission(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteCampaign(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteSubmission(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async getAllAssignedCandidates(): Promise<Array<AssignedCandidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignedCandidates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignedCandidates();
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getApprovedRecruiters(): Promise<Array<SignupRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedRecruiters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedRecruiters();
            return result;
        }
    }
    async getAssignedCandidates(arg0: string, arg1: string): Promise<Array<AssignedCandidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedCandidates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedCandidates(arg0, arg1);
            return result;
        }
    }
    async getCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaigns();
            return result;
        }
    }
    async getSignupRequests(): Promise<Array<SignupRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignupRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignupRequests();
            return result;
        }
    }
    async rejectSignupRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSignupRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSignupRequest(arg0);
            return result;
        }
    }
    async submitSignupRequest(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSignupRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSignupRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCandidateStatus(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidateStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidateStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateClient(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
